<!DOCTYPE html>
<html lang="fr-FR">
	<head>
		<meta charset="UTF-8">
		<title><?=$titre_application?></title>
		
		<!-- Styles -->
		<!-- Reset CSS -->
		<link rel="stylesheet" href="sources/css/reset.css">
		<!-- Bootstrap -->
	    <link rel="stylesheet" href="sources/css/bootstrap/bootstrap.css">
	    <link rel="stylesheet" href="sources/css/bootstrap/bootstrap-responsive.css">
	    <!-- Wild Rider CSS -->
	    <link rel="stylesheet" href="sources/css/styles.css">
		
		<!-- Scripts -->
		<script src="sources/js/jquery.js"></script>
		<script src="sources/js/bootstrap.js"></script>
	</head>

	<body>
		<div id="container">
