<!DOCTYPE HTML>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>Le formulaire</title>

   <form method="post" action="traitement.php">

  <label for="nom">Entrez votre nom </label>
       <input type="text" name="nom" id="nom" /><br>

  <label for="prenom">Entrez votre prenom </label>
       <input type="text" name="prenom" id="prenom" /><br>

  <label for="e-mail">Entrez votre e-mail </label>       
       <input type="email" name="e-mail" id="e-mail" required="email"/><br>

  <label for="prenom">Entrez votre telephone </label>
       <input type="text" name="telephone" id="telephone" /><br>     

	<label for="login">Entrez votre Login </label>
       <input type="text" name="login" id="login" /><br>

    <label for="motdepass"width 45px; >Entrez votre mot de passe </label>
      <input type="password" name="motdepass" /><br>
      
		
     <input type="submit" value="Envoyer" />
   </form>


     <a href="#"> aller vers l ancre</a>

</head>
<body>

</body>
</html>


