	<div id="clients">  <!-- Clients -->
		<table class="table" width="100%">
  		<tr>
		    <th>Nom</th>
    		<th>Prénom</th>
    		<th>Login</th>
    		<th>Téléphone</th>
    		<th>Email</th>
  		</tr>
		<?php
			$i=0;
			while (isset($clients[$i]))
			{?>
			   <tr>

    			<td><?php echo $clients[$i]['nom']?></td>
    			<td><?php echo $clients[$i]['prenom']?></td>
    			<td><?php echo $clients[$i]['login']?></td>
    			<td><?php echo $clients[$i]['telephone']?></td>
    			<td><?php echo $clients[$i]['email']?></td>
    			</tr>
			<?php
			$i++;
			}
		?>
		</table>
	
		<form action='backend.php?page=crclient' method='post'>
	                   
		<input id="creerClient" type="submit" class="btn pull-right" value="Cr&eacute;er client" name="creat_clt">
		</form>

	</div>
	
	<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#wildnav">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a id="client" name="enrclt" href="backend.php?page=crclient" class="navbar-brand">==> creation client</a>
      </div>
    </nav>