<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title><?=$titre_application?></title>
		
		<!-- Styles -->
		<link rel="stylesheet" href="sources/css/reset.css">
	    <link rel="stylesheet" href="sources/css/bootstrap/bootstrap.css">
	    <link rel="stylesheet" href="sources/css/bootstrap/bootstrap-responsive.css">
		
		<!-- Scripts -->
		<script src="sources/js/jquery.js"></script>
		<script src="sources/js/bootstrap.js"></script>
	</head>

	<body>
