<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />

        <link rel="stylesheet" href="sources/css/reset.css">
        <link rel="stylesheet" href="sources/css/bootstrap/css/bootstrap.css">
        <link rel="stylesheet" href="sources/css/stylesheet.css">
        <link rel="stylesheet" href="sources/css/animate.css">
        <link href='http://fonts.googleapis.com/css?family=Ewert' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Ubuntu' rel='stylesheet' type='text/css'>
        <script src="sources/js/jquery.js"></script>
        <title>Backend - WILDRIDER</title>

        
    </head>
 
    <body>

    <div id="container" class="content">
		<h1 id="h1_header">BACK END - WILDRIDER</h1>
        <form action='backend.php' method='post'>
                   
        <input id="quitter" type="submit" class="btn pull-right" value="Quitter" name="quitter">
        </form>