   


  <a href="../index.php"><img id="logo" src="sources/images/logo_w192_h128.jpg"></a>

   <nav class="navbar navbar-default" role="navigation">
    
    <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
      
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#wildnav">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a id="client" href="backend.php?page=accueil" class="navbar-brand">Accueil</a>
      </div>

      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#wildnav">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a id="client" href="backend.php?page=client" class="navbar-brand active">Clients</a>
      </div>
	  
	  <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#wildnav">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a id="client" href="backend.php?page=catalogue" class="navbar-brand active">Catalogue</a>
      </div>
    
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Rechercher</button>
      </form>
      
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Administration</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Evènements <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>

    </div><!-- /.navbar-collapse -->
</nav>
            <!--<ul>
                <a href="index.php?page=accueil"><li>Accueil</li></a>
                <a href="index.php?page=client"><li>Gestion des clients</li></a>
                <a href="index.php?page=produit"><li>Gestion des produits</li></a>
                <a href="index.php?page=categorie"><li>Gestion des catégories</li></a>
                <a href="index.php?page=sscat"><li>Gestion des sous-catégories</li></a>
                <a href="index.php?page=fournisseur"><li>gestion des fournisseurs</li></a>

            </ul> -->

