
	<div id="client">
		<div id="acc_text">
			<p>Gestion du Backend CLIENT </p>
		
		</div>
		<div class="listclt">
		</div>

		<div class="creationclt">
		
		<form name="" id="" action="index.php" method="post" >
		
			<fieldset>
			       <legend>Coordonnées client</legend> <!-- Titre du fieldset -->
			 
			       <p><strong>Civilité:</strong>
			     <label for="label"></label>
			<br />
			       <label for="Mr"></label>
			       <input type="radio" name="civilité" value="Mr" id="Mr" />
			       <label for="label">Mr</label>
			<br />
			       <label for="Mme">
			       <input type="radio" name="civilité" value="Mme" id="Mme" />
			       Mme</label><br />
			       <input type="radio" name="civilité" value="Mlle" id="Mlle" /> <label for="Mlle">Mlle</label><br />
			  </p>
			 
			<p><label><strong>Nom </strong>:</label>
			<input type="text" name="nom" id="nom" value="" /></p>
			<p><label><strong>Pr&eacute;nom</strong> :</label>
			  <input type="text" name="prenom" id="prenom" value="" />
			</p>
			<p><label><strong>Date de naisssance</strong> :</label>
			  <input type="text" name="birthday" id="birthday" value="" size="10" />
			</p>
			<p><label><strong>Téléphone : </strong>:</label>
			<input name="tel" type="text" id="nom" value="" size="10" />
			</p>
			<input type="submit" name="valider" id="valider" value="Enregistrer" />
		</form>
			 
			 
		</div>


	</div>
