<form method="post" action="traitement.php">
	<label for="nom">Entrez votre nom </label><input type="text" name="f_nom" id="nom" />
	<label for="prenom">Entrez votre prenom </label><input type="text" name="f_prenom" id="prenom" />
	<label for="e-mail">Entrez votre e-mail </label><input type="email" name="f_email" id="email" required="email"/>
	<label for="prenom">Entrez votre telephone </label><input type="text" name="f_telephone" id="telephone" />
	<label for="login">Entrez votre Login </label><input type="text" name="f_login" id="login" />
	<label for="motdepass"width 45px; >Entrez votre mot de passe </label><input type="password" name="f_motdepass" /><input type="submit" value="Envoyer" />
</form>

<a href="#"> aller vers l ancre</a>