<!DOCTYPE html>
<!--
	Modèle -->
<html>
    <head>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="css/stylesheet.css">
        <link rel="stylesheet" href="css/animate.css">
        <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Dancing+Script' rel='stylesheet' type='text/css'>
        <script src="sources/jquery.js"></script>
        <title>Wild rider Backend</title>
    </head>
        
    <body>
        <h1> Gestion du Backend </h1>
            <?php require('apps/header.php'); ?>
   
        <div id="menu" class="flip">
            <?php require('apps/menu.php'); ?>
        </div>
        <div id="content">
            <?php require('apps/'.$page.'.php'); ?>
        </div>
        <div id="footer">
            <?php require('apps/footer.php'); ?>
        </div>
    </body>
    <script src="sources/js/backend.js"></script>
</html>

