<!DOCTYPE html>
<html lang="en">
<head>
		<meta charset="UTF-8">

		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		
    	<link href='http://fonts.googleapis.com/css?family=Rock+Salt' rel='stylesheet' type='text/css'>
   		<link href="bootstrap/css/bootstrap.min.css" rel="stylesheet">
    	<link href="boostrap/css/bootstrap.css" rel="stylesheet">
    	<link href="boostrap/css/bootstrap-responsive.css" rel="stylesheet">
    	
	
	<title>articleMoto</title>
	<style type="text/css">
	.article
	{
		width: 80%;
		height: 0 auto;
		
	}
	img
	{
		border-radius: 5%;
		width: 300px;
		height: 300px;
		float: left;
		clear: left;

	}
	img:last-child
	{
		width: 50px;
		height: 50px;
	}
	.list.description
	{
		float: right;
		clear: right;
	}
	li
	{
		text-decoration: none;
		
	}
	input
	{	
		border-radius: 5%;
		float: right;
		clear: right;
	}



	</style>
</head>
<body>
	<div class="article">
		<div class = 'critere'>
		<h1>R6 2014</h1>
		<img src="sportive.jpg" alt="R6">
		
	<!--	<div clas="list">
			<ul>
				<li><a href ="#"></a></li>
				<li><a href="#"></a></li>
				<li><a href="#"></a></li>
				<li><a href="#"></a></li>
				<li><a href="#"></a></li>
			</ul>
		</div>-->
		<h2>Prix &euro; 12 799</h2>
		<input type="submit" value="ajouter au panier">
		</div>
		<div class= 'table'>
		<table>
		<tr>
		<th>description</th>
		<th>Fiche technique</th>
		</tr>
		<tr>
		<td>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia dignissimos minima quo laboriosam debitis ea est facere dolores inventore voluptatem tenetur, dolore nobis, obcaecati eveniet voluptates animi aut nostrum magni?</p>
		</td>
		<td>
		Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus doloremque similique voluptates velit quas illum magnam asperiores quia atque labore facilis laudantium dolores.
		</td>
		</tr>
		</div>
		</div>
	
	
</body>
</html>