<!DOCTYPE html>
<html lang="fr-FR">
	<head>
		<meta charset="UTF-8">
		<title><?=$titre_application?></title>
		
		<!-- Styles -->
		<!-- Reset CSS -->
		<link rel="stylesheet" href="sources/css/reset.css">
		<!-- Bootstrap -->
	    <link rel="stylesheet" href="sources/css/bootstrap/css/bootstrap.css">
	    <link rel="stylesheet" href="sources/css/bootstrap/css/bootstrap-responsive.css">
	    <!-- Wild Rider CSS -->
	    <link rel="stylesheet" href="sources/css/styles.css">
		
		<!-- Scripts -->
		<script src="sources/js/jquery.js"></script>
		<script src="sources/css/bootstrap/js/bootstrap.js"></script>
		<script type="text/javascript">
		/* Fonction pour le détail des compétences et expériences */
			function afficher_detail(id_source, id_cible)
			{
				if($("#" + id_source).text() == "[-] " )
				{
					$("#" + id_source).html("[+] ");
					$("#" + id_cible).css("display", "none");
				}
				else
				{
					$("#" + id_source).html("[-] ");
					$("#" + id_cible).css("display","inline");
					$("#" + id_cible).css("data-type", "Masquer le détail");
				}
			}
		</script>
	</head>

	<body>
		<div id="container" class="content">
