<div id="left-menu">
	<div class="header-bloc">
		<h1 class="header-bloc-text">Catalogue</h1>
	</div>

	<div id="menu-catalogue">
		<ul id="menu-vertical">
			<li><a href="#">Les motos</a>
				<ul>
					<li><a href="#">Motos neuves</a></li>
					<li><a href="#">Motos d'occasion</a></li>
				</ul>
			</li>
			<li><a href="#">Les scooters</a>
				<ul>
					<li><a href="#">Scooters neufs</a></li>
					<li><a href="#">Scooters d'occasion</a></li>
				</ul>
			</li>
			<li><a href="#">Les Quads</a>
				<ul>
					<li><a href="#">Quads neufs</a></li>
					<li><a href="#">Quads d'occasion</a></li>
				</ul>
			</li>
			<li><a href="#">Equipements motard</a>
				<ul>
					<li><a href="#">Les bottes et chaussures</a></li>
					<li><a href="#">Les blousons</a></li>
					<li><a href="#">Les casques</a></li>
					<li><a href="#">Le combinaisons</a></li>
					<li><a href="#">Les gants</a></li>
					<li><a href="#">Les pantalons</a></li>
					<li><a href="#">Equipements de pluie</a></li>
				</ul>
			</li>
			<li><a href="#">Equipements moto</a>
				<ul>
					<li><a href="#">Les bulles</a></li>
					<li><a href="#">Les rétroviseurs</a></li>
					<li><a href="#">Les sélecteurs</a></li>
					<li><a href="#">La sellerie</a></li>
				</ul>
			</li>		</ul>
	</div>
</div>



