<?php 
	// En-tête document HTML
	require("app/document.header.php");
?>

<!-- Ossature de la boutique -->
<div class="row-fluid">
	<header>
		<div id="boutique-header" class="span12 shop-header">
		<div id="logo-header"><?php require("app/app.logo.php"); ?></div>
		
		<div id="widget">
			<div id="language-selector"><?php require("app/app.language.selector.php"); ?></div>
			<div id="customer-zone"><?php require("app/app.customer.area.php"); ?></div>
			<div id="search-zone"><?php require("app/app.search.php") ?></div>
		</div>

		</div>
	</header>
	<nav>
		<div class="span3 shop-left-side">require("nav")</div>
	</nav>
	<section>
		<div class="span6 shop-section">require("section")</div>
	</section>
	<aside>
		<div class="span3 shop-right-side">require("aside")</div>
	</aside>
	<footer>
		<div class="span12 shop-footer">require("footer")</div>
	</footer>

</div>
<?php
	//Pied document HTML
	require("app/document.footer.php");
?>