<div id="left-menu">
	<div class="header-bloc">
		<h1 class="header-bloc-text">Catalogue</h1>
	</div>

	<div id="menu-catalogue">
		<ul class="bloc-menu">
			<li>Les motos
				<ul class="bloc-sous-menu">
					<li>Neuves</li>
					<li>Occasions</li>
				</ul>
			</li>
			<li>Les scooter
				<ul class="bloc-sous-menu">
					<li>Neufs</li>
					<li>Occasions</li>
				</ul>
			</li>
			<li>Les Quads
				<ul class="bloc-sous-menu">
					<li>Neufs</li>
					<li>Occasions</li>
				</ul>
			</li>
		</ul>
	</div>
</div>