<?php 
	// En-tête document HTML
	require("app/document.header.php");
?>

<!-- Ossature de la boutique -->
<div class="row main-content">
	<header>
		<div id="boutique-header" class="span12 shop-header">
			<div id="logo-header">
				<?php require("app/app.logo.php"); ?>
			</div>
			<div id="widget">
				<div id="panier">
					<?php require("app/panier/app.widget.panier.php") ?>
				</div>
				<div id="language-selector">
					<?php require("app/app.language.selector.php"); ?>
				</div>
				<div id="customer-zone">
					<?php
						if($_SESSION["client_registrer"] == 0)
						{
							require("app/app.customer.area.php");
						}
						else
						{
							require("app/client/app.customer.logout.php");
						}
					?>
				</div>
				<div id="search-zone">
					<?php require("app/app.search.php") ?>
				</div>
			</div>
		</div>
	</header>
	<div class="span3 shop-left-side">
		<nav>
			<?php 
				if($_SESSION["client_registrer"] == 1)
				{
					require("app/client/app.bloc-client.php");
				}
			?>
			<?php require("app/app.bloc-navigation.php"); ?>
			<?php require("app/cms/app.bloc-cms.php"); ?>
		</nav>
	</div>	
	<!-- Start : Ecran central -->
	<div class="span6">
		<section>
			<div class="shop-section">
				<!-- Récupère l'url du fichier -->
				<?php require($url); ?>
			</div>
		</section>
	</div>
	<!-- End : Ecran central -->
	<div class="span3 shop-right-side">
		<aside>
			<?php require("app/app.bloc-aside.php"); ?>
		</aside>
	</div>
</div>

<div class="row main-content reinsurance">
	<div class="reinsurance-subdiv">
		<table class="reinsurance-table">
			<tr class="reinsurance-tr">
				<td class="reinsurance-td-img">
					<img src="sources/images/application/reinsurance_telephone.png" alt="Nous appeler au téléphone" />
				</td>
				<td class="reinsurance-table">
					<?=$wr_telephone?> (Lu. de 15H00 à 18H00, du Ma. au Ve. de 10H00 à 18H00)
				</td>
			</tr>
		</table>
	</div>
	
	<div class="reinsurance-subdiv">
		<table class="reinsurance-table">
			<tr class="reinsurance-tr">
				<td class="reinsurance-td-img">
					<img src="sources/images/application/reinsurance_camionette.png" alt="Livraison en 48H00" />
				</td>
				<td class="reinsurance-table">
					Livraison en 48H00
				</td>
			</tr>
		</table>
	</div>
	
	<div class="reinsurance-subdiv">
		<table class="reinsurance-table">
			<tr class="reinsurance-tr">
				<td class="reinsurance-td-img">
					<img src="sources/images/application/reinsurance_retour.png" alt="Retour possible" />
				</td>
				<td class="reinsurance-table">
					Retrour possible, voir conditions au C.G.V.)
				</td>
			</tr>
		</table>
	</div>
	
	<div class="reinsurance-subdiv">
		<table class="reinsurance-table">
			<tr class="reinsurance-tr">
				<td class="reinsurance-td-img">
					<img src="sources/images/application/reinsurance_secure_payment.png" alt="" />
				</td>
				<td class="reinsurance-table">
					Paiement 100% Sécurisé
				</td>
			</tr>
		</table>
	</div>
	
	<div class="reinsurance-subdiv">
		<table class="reinsurance-table">
			<tr class="reinsurance-tr">
				<td class="reinsurance-td-img">
					<img src="sources/images/application/reinsurance_euro.png" alt="" />
				</td>
				<td class="reinsurance-table">
					Paiement en Euros
				</td>
			</tr>
		</table>
	</div>
</div>

<div class="row main-content">
	<footer>
		<div class="span12 shop-footer"><?php require("app/app.footer.php") ?></div>
	</footer>
</div>

<?php
	//Pied document HTML
	require("app/document.footer.php");
?>