<form action="#" method="POST">
	<fieldset>
		<legend class="fieldset-text-footer">Contactez-nous</legend>
		<label class="formulaires-label-footer" for="f_contact_mail">Adresse mail</label><br />
		<input type="mail" name="f_contact_mail" placeholder="Votre adresse mail&hellip;" required id="f_footer_contact_mail" /><br />
		<label class="formulaires-labe-footerl" for="f_contact_message">Votre message</label><br />
		<textarea name="f_contact_message" required id="f_footer_message_textarea" /></textarea><br />
		<input type="submit" name="f_btn_send_message" class="btn btn-primary btn-mini right-align" value="Envoyer" id="f_footer_btn_envoyer" />
	</fieldset>
</form>	
