<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>formmoto</title>
</head>
<body>

	<form action="index.php" method="POST">
<input type="text" name="nom" placeholder="Nom"/>
<br />
<input type="text" name="cylindre" placeholder="cylindre"/>
<br />
<input type="text" name="couleur" placeholder="couleur"/>
<br />
<input type="date" name="annee" placeholder="annee"/>
<br />
<input type="number" name="kilometrage" placeholder="kilometrage"/>
<br/>
<input type="submit" value="Validate"/>
</form>
	
</body>
</html>

